-
  branches:
    only:
      - production

  version: 2.0.4

  configuration: Release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: visor.sln
    verbosity: quiet

  artifacts:
    - path: /.*\.vsix/
      name: VSPackages

-
  branches:
    only:
      - beta

  version: 2.0.5-beta.{build}

  configuration: Release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: visor.sln
    verbosity: normal

  artifacts:
    - path: /.*\.vsix/
      name: VSPackages

-
  branches:
    only:
      - master

  version: 2.0.5-alpha.{build}

  configuration: Debug

  environment:
    COVERALLS_REPO_TOKEN:
      secure: xJST635nD3XTmk90WxWxsVkfWuwJBU+ZZ+NLtlYvxn3Cw/AWEmDz6wwETllN1QXc

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: visor.sln
    verbosity: minimal

  after_test:
    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[Visor*]* -[Visor.*Template*]*" -excludebyattribute:"ExcludeFromCodeCoverage" -hideskipped:All -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single Visor.Lib.Tests\bin\%CONFIGURATION%\Visor.Lib.Tests.dll Visor.Tests\bin\%CONFIGURATION%\Visor.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.1.81\tools\coveralls.net.exe --opencover coverage.xml