-
  branches:
    only:
      - production

  version: 2.0.{build}

  configuration: Release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: quiet

-
  branches:
    only:
      - master

  version: 2.0.{build}-beta

  configuration: Debug

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: minimal
