-
  branches:
    only:
      - production

  version: 2.0.0

  configuration: Release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: visor.sln
    verbosity: quiet

-
  branches:
    only:
      - beta

  version: 2.0.1-beta

  configuration: Debug

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: visor.sln
    verbosity: minimal

-
  branches:
    only:
      - master

  version: 2.0.1.{build}

  configuration: Debug

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  install:
    - nuget restore

  build:
    project: visor.sln
    verbosity: minimal
